### ISSUE TITLE
can't npm start

### ISSUE THREAD

**Issue by Ngmong** [Rajkumardev/chat-GPT#1]
9 verbose lifecycle chatgpt@1.0.0~start: CWD: /chat-GPT-main/backend
10 silly lifecycle chatgpt@1.0.0~start: Args: [ '-c', 'nodemon index.js' ]
11 info lifecycle chatgpt@1.0.0~start: Failed to exec start script
12 verbose stack Error: chatgpt@1.0.0 start: `nodemon index.js`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:400:28)
12 verbose stack     at maybeClose (internal/child_process.js:1088:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)

**Comment by Ngmong** [comment]
> 9 verbose lifecycle chatgpt@1.0.0~start: CWD: /chat-GPT-main/backend 10 silly lifecycle chatgpt@1.0.0~start: Args: [ '-c', 'nodemon index.js' ] 11 info lifecycle chatgpt@1.0.0~start: Failed to exec start script 12 verbose stack Error: chatgpt@1.0.0 start: `nodemon index.js` 12 verbose stack spawn ENOENT 12 verbose stack at ChildProcess. (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18) 12 verbose stack at ChildProcess.emit (events.js:400:28) 12 verbose stack at maybeClose (internal/child_process.js:1088:16) 12 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
